{% set name = "nds2-client-swig" %}
{% set version = "0.16.2" %}
{% set sha256 = "f576a0beae08ddfd222807b96f2cf0f44c1dd1547cd4a4352f65fcc55fc46f28" %}
{% set nds2_client_version = "0.16.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.xz
  url: http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  skip: true  # [win]

requirements:
  build:
    - make
    - cmake >=3.6
    - pkg-config
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - nds2-client >={{ nds2_client_version }}
    - swig >=3.0.7
    - python
    - numpy

test:
  imports:
    - nds2

outputs:
  - name: python-nds2-client
    requirements:
      host:
        - nds2-client >={{ nds2_client_version }}
        - python
        - numpy
      run:
        - nds2-client >={{ nds2_client_version }}
        - python
        - {{ pin_compatible('numpy') }}
    files:
      - lib/python*/site-packages/nds2.py*
      - lib/python*/site-packages/__pycache__/nds2.*.pyc  # [not py27]
      - lib/python*/site-packages/_nds2.so
    test:
      imports:
        - nds2
    about:
      home: https://wiki.ligo.org/DASWG/NDSClient
      license: GPLv3
      license_family: GPL
      license_file: '{{ environ["RECIPE_DIR"] }}/COPYING'
      summary: Python extensions for NDS2
      description: |
        This provides python wrappers for the nds2 client.

about:
  home: https://wiki.ligo.org/DASWG/NDSClient
  license: GPLv3
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/COPYING'
  summary: NDS2 Client interface SWIG wrappings

extra:
  recipe-maintainers:
    - duncanmmacleod
