{% set name = "nds2-client-swig" %}
{% set version = "0.16.12" %}

{% set nds2_client_version = "0.16.8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.bz2
  sha256: d356296f4a137d5e95401b1279e8dbce8b4b7dc8d87d319b09d1a57331caca06
  patches:
    - 0001-python-add-linker-flag-for-the-directory-containing-.patch
    - 0002-python-fix-linking-issues-with-ndscxx.patch
    - 0003-python-use-undefined-dynamic_lookup-on-macos.patch
    - 0004-java-fix-linking-issues-with-ndscxx.patch
    - 0005-Added-JAVA-compatibility-detection-code-to-configura.patch
    - 0006-cx_python-use-sysconfig-instead-of-distutils.patch

build:
  error_overlinking: true  # [not win]
  number: 7

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake >=3.6
    - make  # [unix]
    - pkg-config
    - swig >=3.0.7,<4.1.0a0
  host:
    - nds2-client {{ nds2_client_version }}

test:
  commands:
    - test -f ${PREFIX}/include/nds2-client/nds.i  # [unix]
    - test -f ${PREFIX}/include/nds2-client/nds_swig.hh  # [unix]

outputs:
  - name: nds2-client-swig

  - name: nds2-client-java
    script: build-java.sh  # [not win]
    script: build-java.bat  # [win]
    build:
      error_overlinking: true
      ignore_run_exports_from:
        # we want to ignore libstdcxx, but not libgcc; the latter also comes in through
        # compiler('c'), and conda keeps that despite ignoring the cxx run-exports
        - {{ compiler('cxx') }}  # [not osx]
      # see https://git.ligo.org/nds/nds2-client/-/issues/141
      skip: true  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - cmake >=3.6
        - make  # [not win]
        - openjdk  # [build_platform != target_platform]
        - pkg-config  # [not win]
        - swig >=3.0.7,<4.1.0a0
      host:
        - openjdk
        - nds2-client {{ nds2_client_version }}
        - {{ pin_subpackage('nds2-client-swig', exact=True) }}
      run:
        - nds2-client >={{ nds2_client_version }}
    test:
      commands:
        - if not exist %LIBRARY_LIB%\nds2-client\java\nds2.jar exit 1  # [win]
        - test $(nds-client-config --javaclasspath) == ${PREFIX}/lib/nds2-client/java/nds2.jar  # [unix]
    about:
      home: https://wiki.ligo.org/Computing/NDSClient
      dev_url: https://git.ligo.org/nds/nds2-client.git
      license: GPL-3.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: Java extensions for NDS2
      description: This provides Java wrappers for the nds2 client.

  - name: python-nds2-client
    script: build-python.sh  # [not win]
    script: build-python.bat  # [win]
    build:
      error_overlinking: true
      ignore_run_exports_from:
        - {{ compiler('cxx') }}  # [win]
      skip: true  # [python_impl != 'cpython']
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - cmake >=3.6
        - make  # [unix]
        - pkg-config
        - swig >=3.0.7,<4.1.0a0
        # extras for cross-compiling
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - numpy                               # [build_platform != target_platform]
        - python                              # [build_platform != target_platform]
      host:
        - libpython  # [win]
        - nds2-client {{ nds2_client_version }}
        - {{ pin_subpackage('nds2-client-swig', exact=True) }}
        - numpy
        - python
      run:
        - nds2-client >={{ nds2_client_version }}
        - python
    test:
      requires:
        - pytest
      script: test_nds2.py
    about:
      home: https://wiki.ligo.org/Computing/NDSClient
      dev_url: https://git.ligo.org/nds/nds2-client.git
      license: GPL-3.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: Python extensions for NDS2
      description: This provides python wrappers for the nds2 client.

about:
  home: https://wiki.ligo.org/Computing/NDSClient
  dev_url: https://git.ligo.org/nds/nds2-client.git
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: NDS2 Client interface SWIG wrappings
  description: This provides SWIG interface files for the NDS2 client.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - emaros
