{% set name = "nds2-client-swig" %}
{% set version = "0.16.6" %}
{% set sha256 = "0184eae7cf7eeb1d0a4bb0cf32d57b0a9c60e59912546bd3116e740b2af176b7" %}
{% set nds2_client_version = "0.16.4" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  url: "http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz"
  sha256: "{{ sha256 }}"
  patches:
    - macos-static-python.patch  # [osx]

build:
  error_overdepending: true
  error_overlinking: true
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.6
    - make  # [not win]
    - pkg-config  # [not win]
  host:
    - swig >=3.0.7,<4
    - nds2-client {{ nds2_client_version }}
test:
  commands:
    - test -f ${PREFIX}/include/nds2-client/nds.i  # [unix]
    - test -f ${PREFIX}/include/nds2-client/nds_swig.hh  # [unix]

outputs:
  - name: nds2-client-swig

  - name: python-nds2-client
    script: install-python.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake >=3.6
        - pkg-config  # [not win]
        - make  # [not win]
      host:
        - nds2-client {{ nds2_client_version }}
        - {{ pin_subpackage('nds2-client-swig', exact=True) }}
        - numpy
        - python
        - swig >=3.0.7,<4
      run:
        - nds2-client >={{ nds2_client_version }}
        - python
        - {{ pin_compatible('numpy') }}
    test:
      imports:
        - nds2
    about:
      home: "https://wiki.ligo.org/Computing/NDSClient"
      license: "GPL-3.0-or-later"
      license_family: "GPL"
      license_file: "COPYING"
      summary: "Python extensions for NDS2"
      description: "This provides python wrappers for the nds2 client."

about:
  home: "https://wiki.ligo.org/Computing/NDSClient"
  license: "GPL-3.0-or-later"
  license_family: "GPL"
  license_file: "COPYING"
  summary: "NDS2 Client interface SWIG wrappings"
  description: "This provides SWIG interface files for the NDS2 client."

extra:
  recipe-maintainers:
    - duncanmmacleod
