{% set name = "nds2-client-swig" %}
{% set version = "0.16.11" %}
{% set sha256 = "b4a6fc3e2be91e09f27699779affaad677c4a83ecaaa7b1ed4a77e599f9de3d1" %}
{% set nds2_client_version = "0.16.7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}
  patches:
    - macos-static-python.patch  # [osx]
    - windows-swig-links.patch  # [win]

build:
  error_overdepending: true
  error_overlinking: true  # [not win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.6
    - make  # [not win]
    - pkg-config  # [not win]
    - swig >=3.0.7
  host:
    - nds2-client {{ nds2_client_version }}

test:
  commands:
    - test -f ${PREFIX}/include/nds2-client/nds.i  # [unix]
    - test -f ${PREFIX}/include/nds2-client/nds_swig.hh  # [unix]

outputs:
  - name: nds2-client-swig

  - name: python-nds2-client
    script: install-python.sh  # [not win]
    script: install-python.bat  # [win]
    build:
      error_overdepending: true
      error_overlinking: true
      ignore_run_exports:
        - python  # [not win]
        - vs2015_runtime  # [win]
      skip: true  # [python_impl != 'cpython']
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake >=3.6
        - make  # [not win]
        - pkg-config  # [not win]
        - swig >=3.0.7
      host:
        - libpython  # [win]
        - nds2-client {{ nds2_client_version }}
        - {{ pin_subpackage('nds2-client-swig', exact=True) }}
        - numpy
        - python
      run:
        - nds2-client >={{ nds2_client_version }}
        - {{ pin_compatible('numpy') }}
        - python
    test:
      imports:
        - nds2
    about:
      home: https://wiki.ligo.org/Computing/NDSClient
      dev_url: https://git.ligo.org/nds/nds2-client.git
      license: GPL-3.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: Python extensions for NDS2
      description: This provides python wrappers for the nds2 client.

about:
  home: https://wiki.ligo.org/Computing/NDSClient
  dev_url: https://git.ligo.org/nds/nds2-client.git
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: NDS2 Client interface SWIG wrappings
  description: This provides SWIG interface files for the NDS2 client.

extra:
  recipe-maintainers:
    - duncanmmacleod
