{% set name = "nds2-client-swig" %}
{% set version = "0.16.7" %}
{% set sha256 = "ddb2ceac6baadc58cddc5a980216b4684bd8669e9587b46477831e55b77f0a39" %}
{% set nds2_client_version = "0.16.5" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  url: "http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.bz2"
  sha256: "{{ sha256 }}"
  patches:
    - macos-static-python.patch  # [osx]

build:
  error_overdepending: true
  error_overlinking: true
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.6
    - make  # [not win]
    - pkg-config  # [not win]
  host:
    - swig >=3.0.7,<4
    - nds2-client {{ nds2_client_version }}
test:
  commands:
    - test -f ${PREFIX}/include/nds2-client/nds.i  # [unix]
    - test -f ${PREFIX}/include/nds2-client/nds_swig.hh  # [unix]

outputs:
  - name: nds2-client-swig

  - name: python-nds2-client
    script: install-python.sh
    build:
      error_overdepending: true
      error_overlinking: true
      ignore_run_exports:
        # we don't actually link against libpython
        - python
      skip: true  # [python_impl != 'cpython']
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake >=3.6
        - pkg-config  # [not win]
        - make  # [not win]
      host:
        - nds2-client {{ nds2_client_version }}
        - {{ pin_subpackage('nds2-client-swig', exact=True) }}
        - numpy
        - python
        - swig >=3.0.7,<4
      run:
        - nds2-client >={{ nds2_client_version }}
        - {{ pin_compatible('numpy') }}
        - python
    test:
      imports:
        - nds2
    about:
      home: "https://wiki.ligo.org/Computing/NDSClient"
      license: "GPL-3.0-or-later"
      license_family: "GPL"
      license_file: "COPYING"
      summary: "Python extensions for NDS2"
      description: "This provides python wrappers for the nds2 client."

about:
  home: "https://wiki.ligo.org/Computing/NDSClient"
  license: "GPL-3.0-or-later"
  license_family: "GPL"
  license_file: "COPYING"
  summary: "NDS2 Client interface SWIG wrappings"
  description: "This provides SWIG interface files for the NDS2 client."

extra:
  recipe-maintainers:
    - duncanmmacleod
