{% set name = "nds2-client-swig" %}
{% set version = "0.16.3" %}
{% set sha256 = "08b666adaa0697baaa6f76bf96757fa580fbd02186826b37792691776b84c5c6" %}
{% set nds2_client_version = "0.16.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.xz
  url: http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1001
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.6
    - make  # [not win]
    - pkg-config  # [not win]
    - swig >=3.0.7
  host:
    - nds2-client >={{ nds2_client_version }}

outputs:
  - name: nds2-client-swig
    script: install-interface.sh
    requirements:
      build:
        - cmake >=3.6
        - make  # [not win]
      host:
        - nds2-client >={{ nds2_client_version }}
    test:
      commands:
        - test -f ${PREFIX}/include/nds2-client/nds.i
        - test -f ${PREFIX}/include/nds2-client/nds_swig.hh
    about:
      home: https://wiki.ligo.org/DASWG/NDSClient
      license: GPLv3
      license_family: GPL
      license_file: '{{ environ["RECIPE_DIR"] }}/COPYING'
      summary: SWIG bindings for NDS2
      description: This provides SWIG interface files for the NDS2 client.
  - name: python-nds2-client
    script: install-python.sh
    build:
      activate_in_script: True
      skip: true  # [osx and py==37]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake >=3.6
        - pkg-config  # [not win]
        - make  # [not win]
        - swig >=3.0.7
      host:
        - nds2-client >={{ nds2_client_version }}
        - {{ pin_subpackage('nds2-client-swig', exact=True) }}
        - python
        - numpy
      run:
        - nds2-client >={{ nds2_client_version }}
        - python
        - {{ pin_compatible('numpy') }}
    test:
      imports:
        - nds2
    about:
      home: https://wiki.ligo.org/DASWG/NDSClient
      license: GPLv3
      license_family: GPL
      license_file: '{{ environ["RECIPE_DIR"] }}/COPYING'
      summary: Python extensions for NDS2
      description: |
        This provides python wrappers for the nds2 client.

about:
  home: https://wiki.ligo.org/DASWG/NDSClient
  license: GPLv3
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/COPYING'
  summary: NDS2 Client interface SWIG wrappings

extra:
  recipe-maintainers:
    - duncanmmacleod
